mutation Login(
  $email: String!
  $password: String!
  $rememberMe: Boolean
) {
  login(
    username: $email
    password: $password
    rememberMe: $rememberMe
  ) {
    __typename
    ... on CurrentUser {
      id
      identifier
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}
