mutation SetOrderShippingMethod($shippingMethodId: ID!) {
  setOrderShippingMethod(shippingMethodId: $shippingMethodId) {
    ... on Order {
      ...OrderDetail
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}
