mutation SetCustomerForOrder($input: CreateCustomerInput!) {
  setCustomerForOrder(input: $input) {
    ... on Order {
      ...OrderDetail
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}
